"use client";

import { motion } from "framer-motion";
import { Icons } from "@/components/ui/icons";
import { Badge, Card } from "@/components/ui";
import { EXAMPLE_SITES } from "@/lib/constants";

export function ExampleWebsites() {
  return (
    <section id="examples" className="py-24 px-6 max-w-[1200px] mx-auto">
      <div className="text-center mb-16">
        <Badge>Portfolio</Badge>
        <h2 className="text-[clamp(28px,4vw,40px)] font-bold tracking-[-0.03em] mt-4">
          Example websites
        </h2>
        <p className="text-text-muted mt-3 text-base max-w-[440px] mx-auto">
          Real sites generated by InstantSite for businesses like yours.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {EXAMPLE_SITES.map((ex, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-40px" }}
            transition={{ delay: i * 0.05, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
          >
            <Card hoverable>
              {/* Browser mockup */}
              <div
                className="h-[200px] relative flex flex-col"
                style={{ background: ex.gradient }}
              >
                {/* Chrome bar */}
                <div className="flex items-center gap-1.5 px-3.5 py-2.5 bg-black/30 backdrop-blur-lg">
                  <div className="w-2 h-2 rounded-full bg-white/20" />
                  <div className="w-2 h-2 rounded-full bg-white/20" />
                  <div className="w-2 h-2 rounded-full bg-white/20" />
                  <div className="flex-1 ml-2 h-[22px] rounded-md bg-black/30 flex items-center pl-2.5">
                    <span className="font-mono text-[10px] text-white/40">
                      {ex.name.toLowerCase().replace(/\s+/g, "")}.com
                    </span>
                  </div>
                </div>

                {/* Mock content */}
                <div className="flex-1 p-5 flex flex-col justify-center">
                  <div className="w-3/5 h-2 rounded bg-white/25 mb-2.5" />
                  <div className="w-4/5 h-5 rounded bg-white/15 mb-2" />
                  <div className="w-1/2 h-1.5 rounded bg-white/10 mb-4" />
                  <div className="w-20 h-7 rounded-md bg-white/20" />
                </div>
              </div>

              <div className="px-5 py-4 flex items-center justify-between">
                <div>
                  <h4 className="text-[15px] font-semibold tracking-tight">
                    {ex.name}
                  </h4>
                  <span className="text-[13px] text-text-dim">{ex.type}</span>
                </div>
                <Icons.ExternalLink size={14} className="text-text-dim" />
              </div>
            </Card>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
